import Character, {race} from "../Character";
import {battleAI} from "../AI/BattleAIs";
import {actionPool, defaultActions} from "./BattleActions";

export const characterRoster = {
    orc : {
        peon: new Character({
            name: 'peon',
            race: race.Orc,
            baseHP: 10,
            baseSpeed: 0.35,
            atk: [1,5],
            isPlayable: false,
            combatActions: defaultActions,
            battleAI: battleAI.basic,
        }),
        warrior: new Character({
            name: 'warrior',
            race: race.Orc,
            baseHP: 50,
            baseSpeed: 0.3,
            atk: [5,9],
            isPlayable: false,
            combatActions: defaultActions,
            battleAI: battleAI.basic,
        }),
        warchief: new Character({
            name: 'warchief',
            race: race.Orc,
            baseHP: 100,
            baseSpeed: 0.2,
            atk: [10,15],
            isPlayable: false,
            combatActions: {...defaultActions, heal:actionPool.heal},
            battleAI: battleAI.basic,
        }),
    },
    human : {
        peasant: new Character({
            name: 'gatherer',
            race: race.Human,
            baseHP: 8,
            baseSpeed: 0.4,
            atk: [1,4],
            isPlayable: false,
            combatActions: defaultActions,
            battleAI: battleAI.basic,
        }),
        warrior: new Character({
            name: 'hunter',
            race: race.Human,
            baseHP: 45,
            baseSpeed: 0.4,
            atk: [3,7],
            isPlayable: false,
            combatActions: defaultActions,
            battleAI: battleAI.basic,
        }),
        general: new Character({
            name: 'chieftain',
            race: race.Human,
            baseHP: 90,
            baseSpeed: 0.3,
            atk: [4,12],
            isPlayable: false,
            combatActions: {...defaultActions, heal:actionPool.heal},
            battleAI: battleAI.basic,
        }),
    },
    dwarf : {
        miner: new Character({
            name: 'miner',
            race: race.Dwarf,
            baseHP: 9,
            baseSpeed: 0.35,
            atk: [2,6],
            isPlayable: false,
            combatActions: defaultActions,
            battleAI: battleAI.basic,
        }),
        warrior: new Character({
            name: 'warrior',
            race: race.Dwarf,
            baseHP: 45,
            baseSpeed: 0.45,
            atk: [4,9],
            isPlayable: false,
            combatActions: defaultActions,
            battleAI: battleAI.basic,
        }),
        commander: new Character({
            name: 'commander',
            race: race.Dwarf,
            baseHP: 95,
            baseSpeed: 0.25,
            atk: [9,15],
            isPlayable: false,
            combatActions: {...defaultActions, heal:actionPool.heal},
            battleAI: battleAI.basic,
        }),
    },
    elf : {
        bowyer: new Character({
            name: 'bowyer',
            race: race.Elf,
            baseHP: 6,
            baseSpeed: 0.6,
            atk: [2,6],
            isPlayable: false,
            combatActions: defaultActions,
            battleAI: battleAI.basic,
        }),
        archer: new Character({
            name: 'archer',
            race: race.Elf,
            baseHP: 30,
            baseSpeed: 0.7,
            atk: [2,8],
            isPlayable: false,
            combatActions: defaultActions,
            battleAI: battleAI.basic,
        }),
        lord: new Character({
            name: 'lord',
            race: race.Elf,
            baseHP: 90,
            baseSpeed: 0.9,
            atk: [7,15],
            isPlayable: false,
            combatActions: {...defaultActions, heal:actionPool.heal},
            battleAI: battleAI.basic,
        }),
    },
    goblins : {
        goblin: new Character({
            name: 'mob',
            race: race.Goblin,
            baseHP: 3,
            baseSpeed: 0.6,
            atk: [2,2],
            isPlayable: false,
            combatActions: defaultActions,
            battleAI: battleAI.basic,
        }),
        goblinWarrior: new Character({
            name: 'warrior',
            race: race.Goblin,
            baseHP: 15,
            baseSpeed: 0.7,
            atk: [1,6],
            isPlayable: false,
            combatActions: defaultActions,
            battleAI: battleAI.basic,
        }),
        goblinChieftan: new Character({
            name: 'warboss',
            race: race.Goblin,
            baseHP: 45,
            baseSpeed: 0.9,
            atk: [4,8],
            isPlayable: false,
            combatActions: {...defaultActions, heal:actionPool.heal},
            battleAI: battleAI.basic,
        }),
    }
};
